<template>
  <admin>
    <metatag :title="trans('Find Company')"></metatag>

    <page-header :back="{ to: {name: 'teams.reports'}, text: trans('Back to Reports') }">
      <template v-slot:utilities>
        <a v-if="resource.data.report" class="dt-link text--decoration-none mr-4" @click.prevent="previewPDFOverallReport(resource.data.report)">
          <v-icon small left>mdi-file-pdf</v-icon>
          {{ trans('Preview PDF Report') }}
        </a>
        <p class="mb-0">{{ trans('Generated by') }}: <span clas="mr-3">{{ resource.user.displayname }}</span></p>
      </template>

      <template v-slot:action>
        <div class="mb-3">
          <v-btn v-if="resource.lang == 'en'" :block="$vuetify.breakpoint.smAndDown" large color="primary" @click="goToShowPage('ar')">
            <v-icon small left>mdi-earth</v-icon>
            {{ trans('View Report in Arabic') }}
          </v-btn>
          <v-btn v-else :block="$vuetify.breakpoint.smAndDown" large color="primary" @click="goToShowPage('en')">
            <v-icon small left>mdi-earth</v-icon>
            {{ trans('View Report in English') }}
          </v-btn>
        </div>
        <div>
          <a class="dt-link text--decoration-none mr-4" @click="sendToCrm(item)">
            <v-icon small left>mdi-send</v-icon>
            {{ trans('Send Report to CRM') }}
          </a>
        </div>
      </template>
    </page-header>

    <!-- <template v-if="resource.loading">
      <skeleton-show></skeleton-show>
    </template> -->

    <template>
      <v-card outlined>
        <iframe width="100%" id="iframe-preview" :src="url" frameborder="0"></iframe>
      </v-card>
    </template>
  </admin>
</template>

<script>
import $api from './routes/api'
import $auth from '@/core/Auth/auth'

export default {
  data: () => ({
    resource: {
      lang: window.localStorage.getItem('report:lang') || 'en',
      loading: false,
      data: {},
      user: {},
    },
    url: null,
  }),

  methods: {
    getReportData () {
      let customer = this.$route.params.id
      let user = this.$route.query.user_id || $auth.getId()
      axios.get(
        `/api/v1/reports/overall/customer/${customer}/user/${user}`
      ).then(response => {
        console.log(response.data)
        this.resource.data = response.data
      })
    },

    getReport () {
      let id = this.$route.query.user_id || $auth.getId()
      let customerId = this.$route.params.id
      let lang = this.$route.query.lang || this.resource.lang
      this.$router.replace({query: { user_id: this.$route.query.user_id, lang: lang, from: this.$route.query.from }}).catch(err => {})
      this.url = `/best/preview/reports/overall?user_id=${id}&customer_id=${customerId}&lang=${lang}`
    },

    getUser () {
      this.resource.loading = true
      this.resource.isPrestine = false
      axios.get(
        $api.reports.users.show(parseInt(this.$route.query.user_id))
      ).then(response => {
        this.resource.user = response.data.data
      }).finally(() => {
        this.resource.isPrestine = true
      })
    },

    previewPDFOverallReport (item) {
      window.open(`/best/reports/pdf/preview?report_id=${item.id}&type=overall`, '_blank')
    },

    sendToCrm (item) {
      let data = {
        Id: this.resource.data.token,
        FileNo: this.resource.data.refnum,
        OverallScore: item.value['overall:score'],
        FileContentBase64: item.fileContentBase64,
        'Lessons Learnt': item.value['overall:comment'],
      }
      axios.post(
        $api.crm.save(), data
      ).then(response => {
      })
    },

    downloadReport () {
      window.location.href = `/reports/${this.$route.params.report}/download`
      // axios.get(
      //   `/api/v1/reports/${this.$route.params.report}/download`
      // ).then(response => {
      //   let blob = new Blob([response.data], { type: 'application/pdf' })
      //   let link = document.createElement('a')
      //   link.href = window.URL.createObjectURL(blob)
      //   link.download = `Report.pdf`
      //   link.click()
      // })
    },

    setIframeHeight () {
      this.resource.loading = true
      document.querySelector('iframe').addEventListener('load', function (e) {
        var iframe = this
        var iframeWin = iframe.contentWindow || iframe.contentDocument.parentWindow

        if (iframeWin.document.body) {
          iframe.height = iframeWin.document.documentElement.scrollHeight || iframeWin.document.body.scrollHeight
        }
      })
      this.resource.loading = false
    },

    goToShowPage (lang = 'en') {
      window.localStorage.setItem('report:lang', lang)
      this.resource.lang = lang
      this.$router.push({
        name: 'teams.overall',
        params: {
          id: this.$route.params.id,
          report: this.$route.params.report
        },
        query: {
          lang: lang,
          type: 'overall',
          from: this.$route.query.from,
          user_id: this.$route.query.user_id
        }
      }).catch(err => {})
      this.$router.go()
    },
  },

  mounted () {
    this.setIframeHeight()
    this.getReportData()
    this.getReport()
    this.getUser()
  },
}
</script>
