<?php

return [
    'fmpi' => [
        'list' => [
            '7' =>  ['Documentation' => 'Adopt financial analytics in management reporting'],
            '8' =>  ['Documentation' => 'Review relevant financial indicators'],
            '10' => ['Documentation' => 'Review scope of financial management report'],
            '11' => ['Documentation' => 'Align financial reporting to management requirements'],
            '18' => ['Documentation' => 'Align financial forecasting to organisation strategic plan'],
            '21'=> ['Documentation' => 'Review templates & forms for financial projections'],
            '1' =>['ICT' =>  'Establish inventory management system'],
            '12' =>['ICT' =>  'Implement financial monitoring system'],
            '16' => ['ICT' => 'Implement financial analytics dashboard'],
            '20' => ['ICT' => 'Implement predictive analytics system to facilitate financial forecasts'],
            '23' => ['ICT' => 'Implement Enterprise Resource Planning (ERP) solution'],
            '4'  =>  ['Personnel' => 'Conduct inventory management training'],
            '5' =>  ['Personnel' => 'Train & mentor finance employees in preparing effective financial management report'],
            '6' =>  ['Personnel' =>'Empower and equip appropriate staff to oversee financial management'],
            '14' => ['Personnel' => 'Develop competency capabilities within finance team'],
            '19' => ['Personnel' => 'Equip HODs with relevant financial management literacy'],
            '27' => ['Personnel' =>'Segregate key financial roles to relevant representatives in the organisation'],
            '2' => ['Process' => 'Review effectiveness of inventory management practices'],
            '3' => ['Process' => 'Establish periodic updates of cost of goods sold'],
            '9' => ['Process' => 'Systemise financial analysis report for management'],
            '13' => ['Process' => 'Improve alignment of financial management system to business operations'],
            '15' => ['Process' => 'Review financial operational processes to maintain relevance'],
            '17' => ['Process' => 'Implement financial planning practices'],
            '22' => ['Process' => 'Integrate financial manag    ement systems effectively'],
            '24' => ['Process' => 'Conduct comprehensive 3rd party due diligence'],
            '25' => ['Process' => 'Conduct periodic risk assessments'],
            '26' => ['Process' => 'Conduct regular internal audits'],
            '28' => ['Process' => 'Establish a whistleblowing system'],
            '29' => ['Process' => 'Conduct periodic external audit to review risk management practices'],
        ],
        'count' => 10,
    ],
    'bspi' => [
        'list' => [
            '3' => ['Documentation' => 'Conduct employee engagement survey'],
            '6' => ['Documentation' => 'Review work improvement schemes'],
            '12' => ['Documentation' => 'Develop a company-specific business continuity management manual'],
            '19' => ['Documentation' => 'Set-up Strategic Management framework'],
            '29' => ['Documentation' => 'Review organisation documentation processes'],
            '4' => ['ICT' => 'Acquire end-to-end industry-specific operating systems'],
            '11' => ['ICT' => 'Adopt performance analytics system'],
            '24' => ['ICT' => 'Implement collaborative tools for employee engagements'],
            '25' => ['ICT' => "Review & align effectiveness of collaborative tools' purposes"],
            '2' => ['Personnel' => 'Review leadership communication & management strategies'],
            '5' => ['Personnel' => 'Conduct skills upgrading to familiarise with adopted technology'],
            '8' => ['Personnel' => 'Conduct leadership program'],
            '13' => ['Personnel' => 'Attend Business Continuity Management training'],
            '17' => ['Personnel' => 'Enhance employee engagement on risk management'],
            '28' => ['Personnel' => 'Review staff reward system'],
            '1' => ['Process' => 'Introduce appropriate periodic management communication sessions'],
            '7' => ['Process' => 'Perform review of technology best practices within sector'],
            '9' => ['Process' => 'Develop a system promoting innovation'],
            '10' => ['Process' => 'Review technology procurement process'],
            '14' => ['Process' => 'Review employee engagement communication on business continuity practices'],
            '15' => ['Process' => 'Implement Risk Management Framework'],
            '16' => ['Process' => 'Conduct gap review of existing risk management strategies'],
            '18' => ['Process' => 'Implement employee engagement strategies relating to organisation strategies & direction'],
            '20' => ['Process' => 'Review employee engagement strategies'],
            '21' => ['Process' => 'Review Strategic Management framework'],
            '22' => ['Process' => 'Engage employees in Strategic Planning'],
            '23' => ['Process' => 'Organise employees into strategy-centric working committees'],
            '26' => ['Process' => 'Review integration of communication tools across work functions'],
            '27' => ['Process' => 'Review technology adoption within work processes'],
            '30' => ['Process' => 'Review workflow processes'],
        ],
        'count' => 10,
    ],
    'pmpi' =>  [
        'list' => [
            '1' => ['Documentation' => 'Adopt swimlane process map'],
            '2' => ['Documentation' => 'Implement a family of measures'],
            '3' => ['Documentation' => 'Introduce Structured Documentation Mangement System'],
            '6' => ['Documentation' => 'Include Cost of Quality measure into management report'],
            '8' => ['Documentation' => 'Conduct Employee Survey concerning productivity practices'],
            '11' => ['Documentation' => 'Adopt Fishbone Diagram tool in problem solving'],
            '15' => ['Documentation' => 'Adopt the Pareto Chart when prioritising intervention strategies'],
            '17' => ['Documentation' => 'Adopt the SIPOC Diagram when mapping value chain'],
            '18' => ['Documentation' => 'Adopt PICK Chart as a tool to organise productivity ideas'],
            '4' => ['ICT' => 'Improve on the Employee Scheduling'],
            '10' => ['ICT' => 'Adopt IMPACT Assessment Tools to assess productivity'],
            '23' => ['ICT' => 'Set up Work Improvement Team (WIT) System'],
            '5' => ['Personnel' => 'Implement Customer Satisfaction Analysis'],
            '9' => ['Personnel' => 'Conduct a training Needs Analysis'],
            '16' => ['Personnel' => 'Develop & Implement Mentorship Programme'],
            '7' => ['Process' => 'Adopt Process Benchmarking to match industry best practices'],
            '12' => ['Process' => 'Appoint or Conduct Market Research periodically'],
            '13' => ['Process' => 'Review IMPACT Framework'],
            '14' => ['Process' => 'Introduce Plan, Do, Check, Act (PDCA) Process'],
            '19' => ['Process' => 'Ensure more stakeholder involvement during appropriate service development stages'],
            '20' => ['Process' => 'Keep track of processes through benchmarking & continual improvement'],
            '21' => ['Process' => 'Improve organisation policy deployment'],
            '22' => ['Process' => 'Set up Work Improvement Team (WIT) System']
        ],
        'count' => 10,
    ],
    'hrpi' => [
        'list' => [
            '3' => ['Documentation' => 'Review manpower regulations & policies'],
            '7' => ['Documentation' => 'Review & align all Job Descriptions (JDs)'],
            '8' => ['Documentation' => 'Develop JD Framework'],
            '11' => ['Documentation' => 'Develop compensation philosophy'],
            '19' => ['Documentation' => 'Develop a Training Needs Analysis'],
            '21' => ['Documentation' => 'Structure Personal Development Plan'],
            '23' => ['Documentation' => 'Develop or Promote career progression strategy'],
            '29' => ['Documentation' => 'Regular Manual Updates'],
            '31' => ['Documentation' => 'Incorporate Core Competencies'],
            '9' => ['ICT' => 'Review existing recruitment & selection (R&S) system'],
            '12' => ['ICT' => 'Ease access to Compensation & Benefits information'],
            '14' => ['ICT' => 'Implement Comprehensive Performance Assessment'],
            '22' => ['ICT' => 'Develop appropriate knowledge-bank platforms '],
            '27' => ['ICT' => 'Develop effective Staff Communication platforms'],
            '10' => ['Personnel' => 'Conduct Comprehensive Induction'],
            '13' => ['Personnel' => 'Review & align compensation & benefit to sector practices'],
            '15' => ['Personnel' => 'Align company goals with performance objectives'],
            '18' => ['Personnel' => 'Create learning & development culture'],
            '20' => ['Personnel' => 'Adopt developmental management approach'],
            '25' => ['Personnel' => 'Succession Management'],
            '1' => ['Process' => 'Monitor & review labour market trends'],
            '2' => ['Process' => 'Align manpower strength with organisational strategies'],
            '4' => ['Process' => 'Integrate workforce planning with Business Planning'],
            '5' => ['Process' => 'Develop dynamic workforce planning'],
            '6' => ['Process' => 'Set up recruitment & selection framework'],
            '16' => ['Process' => 'Conduct performance feedback'],
            '17' => ['Process' => 'Review performance communication strategies'],
            '24' => ['Process' => 'Implement Leadership Development Programme for High Performers'],
            '26' => ['Process' => 'Adopt 3 Ps (Purpose, Process & Plan) in Employee Engagement'],
            '28' => ['Process' => 'Evaluate & Refine Employee Engagement & Communication Strategies'],
            '30' => ['Process' => 'Develop Competency Framework'],
        ],
        'count' => 8,
    ]
];
